\input texinfo   @c -*- Mode: Texinfo; Mode: auto-fill -*-
@c %**start of header
@setfilename cl-plplot.info
@settitle Cl-plplot User Manual

@copying
Copyright @copyright{} 2006 Hazen P. Babcock <hbabcockos1 at mac.com>

@quotation
Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the ``Software''), to deal in the Software without
restriction, including without limitation the rights to use, copy,
modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

@sc{The software is provided ``as is'', without warranty of any kind,
express or implied, including but not limited to the warranties of
merchantability, fitness for a particular purpose and noninfringement.
In no event shall the authors or copyright holders be liable for any
claim, damages or other liability, whether in an action of contract,
tort or otherwise, arising from, out of or in connection with the
software or the use or other dealings in the software.}
@end quotation
@end copying

@titlepage
@title Cl-plplot User Manual
@vskip 0pt plus 1filll
October 13, 2006

@page
@vskip 0pt plus 1fill
@insertcopying
@end titlepage

@menu
* Introduction::
* The Low Level Interface to PLplot::
* The High Level Plotting Package::
@end menu

@node Introduction
@chapter Introduction
The introduction

@node The Low Level Interface to PLplot
@chapter The Low Level Interface to PLplot
The low level interface to PLplot

@node The High Level Plotting Package
@chapter The High Level Plotting Package
The high level plotting package

@bye
